---
title: "Project Code - Race"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(lubridate)
library(arrow)
```

```{r import saved data, echo=FALSE}
data_path <- "/Users/lisawu/Downloads/"
applications <- read_parquet(paste0(data_path,"project_dataframe.parquet"))
```

```{r rough dataset}
RoughData <-applications %>%
  filter(disposal_type %in% c("ISS", "ABN")) %>%
  select(filing_date, appl_status_date,tenure_days, appl_status_code,disposal_type,gender, race, wg, examiner_art_unit, examiner_id, tc) %>%
  mutate(status_date = as.Date(appl_status_date, format = "%d%b%Y %H:%M:%S")) %>%
  mutate(processing_days = as.numeric(status_date - filing_date))
```

```{r clean the RoughData and name it }
dataset <- RoughData %>%
  # changed variable name 
  rename(id=examiner_id, art_unit = examiner_art_unit) %>%
  # created a new table with selected variables
  select(id, gender, race, disposal_type, status_date, filing_date, processing_days, tc, wg, art_unit, tenure_days ) %>%
  # drop all NAs for gender
  drop_na(gender) %>%
  # drop all NAs for status date
  drop_na(processing_days) %>%
  #filter wg 1600, 1700, 2100, 2400
  filter(!(wg == "1600"), !(wg == "1700"), !(wg == "2100"), !(wg == "2400"))
```

```{r processing time of race in organization level by histogram}
average_race_matrix_organization <- dataset %>%
  group_by(disposal_type, race) %>%
  summarize(average_processing_days_race = mean(processing_days, na.rm = TRUE)) %>%
  pivot_wider(names_from = disposal_type, values_from = average_processing_days_race)

# Convert the matrix to a long format
average_race_matrix_organization_long <- average_race_matrix_organization %>%
  gather(disposal_type, average_processing_days_race, -race)

# Create the bar chart
bar_chart_2 <- ggplot(average_race_matrix_organization_long, aes(x = race, y = average_processing_days_race, fill = disposal_type)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Processing Time by Race Across Organization",
       x = "Race",
       y = "Average Processing Days",
       fill = "Disposal Type") +
  facet_wrap(~disposal_type) +
  stat_summary(fun = "mean", geom = "text", vjust = -0.5, size = 3, 
               aes(label = round(average_processing_days_race, digits = 1)), 
               position = position_dodge(width = 0.9))
bar_chart_2
```

```{r create a table just for tc}
tc_dataframe <- dataset %>%
  select (gender, race, disposal_type, processing_days, tc,tenure_days)
```


```{r processing time of race in tc level by histogram}
# Calculate average processing days per category
averages_tc_race <- tc_dataframe %>%
  group_by(tc, race, disposal_type) %>%
  summarize(average_processing_days_race_tc = mean(processing_days))

# Create the bar chart with stacked bars
ggplot(averages_tc_race, aes(x = as.factor(tc), y = average_processing_days_race_tc, fill = race)) +
  geom_bar(stat = "identity", position = "stack") +
  facet_wrap(~disposal_type) +
  labs(title = "Processing Time by Race Across TCs",x = "TC", y = "Average Processing Days", fill = "Race") +
  stat_summary(fun = "mean", geom = "text", vjust = -0.5, size = 3, 
               aes(label = round(average_processing_days_race_tc, digits = 1)), 
               position = position_stack(vjust = 0.5))

```


```{r create a table just for wg}
wg_dataframe <- dataset %>%
  select (gender, race, disposal_type, processing_days, tc,tenure_days,wg)
```


```{r processing time of race in wg level by histogram ABN}
filtered_table_wg_0 <- wg_dataframe %>%
  filter (disposal_type == "ABN") 

# Calculate average processing days per category
averages_race_wg <- filtered_table_wg_0 %>%
  group_by(wg, race, disposal_type) %>%
  summarize(average_processing_days_race_wg = mean(processing_days))

# Create the bar chart
ggplot(averages_race_wg, aes(x = as.factor(wg), y = average_processing_days_race_wg, fill = race)) +
  geom_bar(stat = "identity", position = "stack") +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Disposal Typel: ABN, Processing Time by Race Across Workgroups", x = "Workgroup", y = "Average Processing Days", fill = "Race") 
```
```{r processing time of race in wg 1600 level by histogram ABN}
filtered_table_wg_1 <- wg_dataframe%>%
  filter(wg >= 1600 & wg <= 1690) %>%
  filter (disposal_type == "ABN")

# Calculate average processing days per category
averages_race_wg_ABN_1 <- filtered_table_wg_1 %>%
  group_by(wg, race, disposal_type) %>%
  summarize(average_processing_days_race_wg_1 = mean(processing_days))

# Create the bar chart
ggplot(averages_race_wg_ABN_1, aes(x = as.factor(wg), y = average_processing_days_race_wg_1, fill = race)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Disposal Typel: ABN, Processing Time by Race Across Workgroup 1600", x = "Workgroup", y = "Average Processing Days", fill = "Race") +
  stat_summary(fun = "mean", geom = "text", vjust = -0.5, size = 2.2, 
               aes(label = round(average_processing_days_race_wg_1, digits = 0)), 
               position = position_dodge(width = 0.9))
```
```{r processing time of race in wg 1700 level by histogram ABN}
filtered_table_wg_2 <- wg_dataframe%>%
  filter(wg >= 1700 & wg <= 1790) %>%
  filter (disposal_type == "ABN")

# Calculate average processing days per category
averages_race_wg_ABN_2 <- filtered_table_wg_2 %>%
  group_by(wg, race, disposal_type) %>%
  summarize(average_processing_days_race_wg_2 = mean(processing_days))

# Create the bar chart
ggplot(averages_race_wg_ABN_2, aes(x = as.factor(wg), y = average_processing_days_race_wg_2, fill = race)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Disposal Typel: ABN, Processing Time by Race Across Workgroup 1700", x = "Workgroup", y = "Average Processing Days", fill = "Race") +
  stat_summary(fun = "mean", geom = "text", vjust = -0.5, size = 2.2, 
               aes(label = round(average_processing_days_race_wg_2, digits = 0)), 
               position = position_dodge(width = 0.9))
```

```{r processing time of race in wg 2100 level by histogram ABN}
filtered_table_wg_3 <- wg_dataframe%>%
  filter(wg >= 2100 & wg <= 2190) %>%
  filter (disposal_type == "ABN")

# Calculate average processing days per category
averages_race_wg_ABN_3 <- filtered_table_wg_3 %>%
  group_by(wg, race, disposal_type) %>%
  summarize(average_processing_days_race_wg_3 = mean(processing_days))

# Create the bar chart
ggplot(averages_race_wg_ABN_3, aes(x = as.factor(wg), y = average_processing_days_race_wg_3, fill = race)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Disposal Typel: ABN, Processing Time by Race Across Workgroup 2100", x = "Workgroup", y = "Average Processing Days", fill = "Race") +
  stat_summary(fun = "mean", geom = "text", vjust = -0.5, size = 2.2, 
               aes(label = round(average_processing_days_race_wg_3, digits = 0)), 
               position = position_dodge(width = 0.9))
```

```{r processing time of race in wg 2400 level by histogram ABN}
filtered_table_wg_4 <- wg_dataframe%>%
  filter(wg >= 2400 & wg <= 2490) %>%
  filter (disposal_type == "ABN")

# Calculate average processing days per category
averages_race_wg_ABN_4 <- filtered_table_wg_4 %>%
  group_by(wg, race, disposal_type) %>%
  summarize(average_processing_days_race_wg_4 = mean(processing_days))

# Create the bar chart
ggplot(averages_race_wg_ABN_4, aes(x = as.factor(wg), y = average_processing_days_race_wg_4, fill = race)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Disposal Typel: ABN, Processing Time by Race Across Workgroup 2400", x = "Workgroup", y = "Average Processing Days", fill = "Race") +
  stat_summary(fun = "mean", geom = "text", vjust = -0.5, size = 2.2, 
               aes(label = round(average_processing_days_race_wg_4, digits = 0)), 
               position = position_dodge(width = 0.9))
```



```{r processing time of race in wg level by histogram ISS}
filtered_table_wg_9 <- wg_dataframe%>%
  filter (disposal_type == "ISS")

# Calculate average processing days per category
averages_race_wg_2 <- filtered_table_wg_9 %>%
  group_by(wg, race, disposal_type == "ISS") %>%
  summarize(average_processing_days_race_wg_2 = mean(processing_days))

# Create the bar chart
ggplot(averages_race_wg_2, aes(x = as.factor(wg), y = average_processing_days_race_wg_2, fill = race)) +
  geom_bar(stat = "identity", position = "stack") +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Disposal Typel: ISS, Processing Time by Race Across Workgroups", x = "Workgroup", y = "Average Processing Days", fill = "Race") 
```

```{r processing time of race in wg 1600 level by histogram ISS}
filtered_table_wg_5 <- wg_dataframe%>%
  filter(wg >= 1600 & wg <= 1690) %>%
  filter (disposal_type == "ISS")

# Calculate average processing days per category
averages_race_wg_ISS_5 <- filtered_table_wg_5 %>%
  group_by(wg, race, disposal_type) %>%
  summarize(average_processing_days_race_wg_5 = mean(processing_days))

# Create the bar chart
ggplot(averages_race_wg_ISS_5, aes(x = as.factor(wg), y = average_processing_days_race_wg_5, fill = race)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Disposal Typel: ISS, Processing Time by Race Across Workgroup 1600", x = "Workgroup", y = "Average Processing Days", fill = "Race") +
  stat_summary(fun = "mean", geom = "text", vjust = -0.5, size = 2.2, 
               aes(label = round(average_processing_days_race_wg_5, digits = 0)), 
               position = position_dodge(width = 0.9))
```


```{r processing time of race in wg 1700 level by histogram ISS}
filtered_table_wg_6 <- wg_dataframe%>%
  filter(wg >= 1700 & wg <= 1790) %>%
  filter (disposal_type == "ISS")

# Calculate average processing days per category
averages_race_wg_ISS_6 <- filtered_table_wg_6 %>%
  group_by(wg, race, disposal_type) %>%
  summarize(average_processing_days_race_wg_6 = mean(processing_days))

# Create the bar chart
ggplot(averages_race_wg_ISS_6, aes(x = as.factor(wg), y = average_processing_days_race_wg_6, fill = race)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Disposal Typel: ISS, Processing Time by Race Across Workgroup 1700", x = "Workgroup", y = "Average Processing Days", fill = "Race") +
  stat_summary(fun = "mean", geom = "text", vjust = -0.5, size = 2.2, 
               aes(label = round(average_processing_days_race_wg_6, digits = 0)), 
               position = position_dodge(width = 0.9))
```

```{r processing time of race in wg 2100 level by histogram ISS}
filtered_table_wg_7 <- wg_dataframe%>%
  filter(wg >= 2100 & wg <= 2190) %>%
  filter (disposal_type == "ISS")

# Calculate average processing days per category
averages_race_wg_ISS_7 <- filtered_table_wg_7 %>%
  group_by(wg, race, disposal_type) %>%
  summarize(average_processing_days_race_wg_7 = mean(processing_days))

# Create the bar chart
ggplot(averages_race_wg_ISS_7, aes(x = as.factor(wg), y = average_processing_days_race_wg_7, fill = race)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Disposal Typel: ISS, Processing Time by Race Across Workgroup 2100", x = "Workgroup", y = "Average Processing Days", fill = "Race") +
  stat_summary(fun = "mean", geom = "text", vjust = -0.5, size = 2.2, 
               aes(label = round(average_processing_days_race_wg_7, digits = 0)), 
               position = position_dodge(width = 0.9))
```

```{r processing time of race in wg 2400 level by histogram ISS}
filtered_table_wg_8 <- wg_dataframe%>%
  filter(wg >= 2400 & wg <= 2490) %>%
  filter (disposal_type == "ISS")

# Calculate average processing days per category
averages_race_wg_ISS_8 <- filtered_table_wg_8 %>%
  group_by(wg, race, disposal_type) %>%
  summarize(average_processing_days_race_wg_8 = mean(processing_days))

# Create the bar chart
ggplot(averages_race_wg_ISS_8, aes(x = as.factor(wg), y = average_processing_days_race_wg_8, fill = race)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Disposal Typel: ISS, Processing Time by Race Across Workgroup 2400", x = "Workgroup", y = "Average Processing Days", fill = "Race") +
  stat_summary(fun = "mean", geom = "text", vjust = -0.5, size = 2.2, 
               aes(label = round(average_processing_days_race_wg_8, digits = 0)), 
               position = position_dodge(width = 0.9))
```